/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiPaymentOtpRouteImport } from './routes/api/payment-otp'
import { Route as ApiPaymentInfoRouteImport } from './routes/api/payment-info'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as DashboardProductsIndexRouteImport } from './routes/_dashboard/products/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/_dashboard/orders/index'
import { Route as DashboardCustomersIndexRouteImport } from './routes/_dashboard/customers/index'
import { Route as DashboardAddProductIndexRouteImport } from './routes/_dashboard/add-product/index'
import { Route as DashboardAccountIndexRouteImport } from './routes/_dashboard/account/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ApiProductsByIdRouteImport } from './routes/api/products/by-id'
import { Route as ApiProductsByCategoryRouteImport } from './routes/api/products/by-category'
import { Route as ApiCustomerByNameRouteImport } from './routes/api/customer/by-name'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardProductsSlugRouteImport } from './routes/_dashboard/products/$slug'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentOtpRoute = ApiPaymentOtpRouteImport.update({
  id: '/api/payment-otp',
  path: '/api/payment-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentInfoRoute = ApiPaymentInfoRouteImport.update({
  id: '/api/payment-info',
  path: '/api/payment-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCustomersIndexRoute = DashboardCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAddProductIndexRoute =
  DashboardAddProductIndexRouteImport.update({
    id: '/add-product/',
    path: '/add-product/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiProductsByIdRoute = ApiProductsByIdRouteImport.update({
  id: '/by-id',
  path: '/by-id',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiProductsByCategoryRoute = ApiProductsByCategoryRouteImport.update({
  id: '/by-category',
  path: '/by-category',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiCustomerByNameRoute = ApiCustomerByNameRouteImport.update({
  id: '/api/customer/by-name',
  path: '/api/customer/by-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsSlugRoute = DashboardProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/payment-info': typeof ApiPaymentInfoRoute
  '/api/payment-otp': typeof ApiPaymentOtpRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$slug': typeof DashboardProductsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/customer/by-name': typeof ApiCustomerByNameRoute
  '/api/products/by-category': typeof ApiProductsByCategoryRoute
  '/api/products/by-id': typeof ApiProductsByIdRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/account/': typeof DashboardAccountIndexRoute
  '/add-product/': typeof DashboardAddProductIndexRoute
  '/customers/': typeof DashboardCustomersIndexRoute
  '/orders/': typeof DashboardOrdersIndexRoute
  '/products/': typeof DashboardProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/payment-info': typeof ApiPaymentInfoRoute
  '/api/payment-otp': typeof ApiPaymentOtpRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$slug': typeof DashboardProductsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/customer/by-name': typeof ApiCustomerByNameRoute
  '/api/products/by-category': typeof ApiProductsByCategoryRoute
  '/api/products/by-id': typeof ApiProductsByIdRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/account': typeof DashboardAccountIndexRoute
  '/add-product': typeof DashboardAddProductIndexRoute
  '/customers': typeof DashboardCustomersIndexRoute
  '/orders': typeof DashboardOrdersIndexRoute
  '/products': typeof DashboardProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/api/orders': typeof ApiOrdersRoute
  '/api/payment-info': typeof ApiPaymentInfoRoute
  '/api/payment-otp': typeof ApiPaymentOtpRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/products/$slug': typeof DashboardProductsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/customer/by-name': typeof ApiCustomerByNameRoute
  '/api/products/by-category': typeof ApiProductsByCategoryRoute
  '/api/products/by-id': typeof ApiProductsByIdRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/_dashboard/account/': typeof DashboardAccountIndexRoute
  '/_dashboard/add-product/': typeof DashboardAddProductIndexRoute
  '/_dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/_dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/_dashboard/products/': typeof DashboardProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/orders'
    | '/api/payment-info'
    | '/api/payment-otp'
    | '/api/products'
    | '/products/$slug'
    | '/api/auth/$'
    | '/api/customer/by-name'
    | '/api/products/by-category'
    | '/api/products/by-id'
    | '/login/'
    | '/signup/'
    | '/account/'
    | '/add-product/'
    | '/customers/'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/orders'
    | '/api/payment-info'
    | '/api/payment-otp'
    | '/api/products'
    | '/products/$slug'
    | '/api/auth/$'
    | '/api/customer/by-name'
    | '/api/products/by-category'
    | '/api/products/by-id'
    | '/login'
    | '/signup'
    | '/account'
    | '/add-product'
    | '/customers'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/api/orders'
    | '/api/payment-info'
    | '/api/payment-otp'
    | '/api/products'
    | '/_dashboard/'
    | '/_dashboard/products/$slug'
    | '/api/auth/$'
    | '/api/customer/by-name'
    | '/api/products/by-category'
    | '/api/products/by-id'
    | '/_auth/login/'
    | '/_auth/signup/'
    | '/_dashboard/account/'
    | '/_dashboard/add-product/'
    | '/_dashboard/customers/'
    | '/_dashboard/orders/'
    | '/_dashboard/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiPaymentInfoRoute: typeof ApiPaymentInfoRoute
  ApiPaymentOtpRoute: typeof ApiPaymentOtpRoute
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCustomerByNameRoute: typeof ApiCustomerByNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-otp': {
      id: '/api/payment-otp'
      path: '/api/payment-otp'
      fullPath: '/api/payment-otp'
      preLoaderRoute: typeof ApiPaymentOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-info': {
      id: '/api/payment-info'
      path: '/api/payment-info'
      fullPath: '/api/payment-info'
      preLoaderRoute: typeof ApiPaymentInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/products/': {
      id: '/_dashboard/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/orders/': {
      id: '/_dashboard/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/customers/': {
      id: '/_dashboard/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof DashboardCustomersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/add-product/': {
      id: '/_dashboard/add-product/'
      path: '/add-product'
      fullPath: '/add-product/'
      preLoaderRoute: typeof DashboardAddProductIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/account/': {
      id: '/_dashboard/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/products/by-id': {
      id: '/api/products/by-id'
      path: '/by-id'
      fullPath: '/api/products/by-id'
      preLoaderRoute: typeof ApiProductsByIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/products/by-category': {
      id: '/api/products/by-category'
      path: '/by-category'
      fullPath: '/api/products/by-category'
      preLoaderRoute: typeof ApiProductsByCategoryRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/customer/by-name': {
      id: '/api/customer/by-name'
      path: '/api/customer/by-name'
      fullPath: '/api/customer/by-name'
      preLoaderRoute: typeof ApiCustomerByNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/products/$slug': {
      id: '/_dashboard/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof DashboardProductsSlugRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProductsSlugRoute: typeof DashboardProductsSlugRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
  DashboardAddProductIndexRoute: typeof DashboardAddProductIndexRoute
  DashboardCustomersIndexRoute: typeof DashboardCustomersIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProductsSlugRoute: DashboardProductsSlugRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
  DashboardAddProductIndexRoute: DashboardAddProductIndexRoute,
  DashboardCustomersIndexRoute: DashboardCustomersIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ApiProductsRouteChildren {
  ApiProductsByCategoryRoute: typeof ApiProductsByCategoryRoute
  ApiProductsByIdRoute: typeof ApiProductsByIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsByCategoryRoute: ApiProductsByCategoryRoute,
  ApiProductsByIdRoute: ApiProductsByIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiPaymentInfoRoute: ApiPaymentInfoRoute,
  ApiPaymentOtpRoute: ApiPaymentOtpRoute,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCustomerByNameRoute: ApiCustomerByNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
